apiVersion: v1
kind: Secret
metadata:
  name: postgres-sec
type: Opaque
data:
#Replace YOUR_DATABASE_PASSWORD with a base64 encoded string for postgres password
  POSTGRES_PASSWORD: YOUR_DATABASE_PASSWORD
  POSTGRES_USER: YOUR_DATABASE_USERNAME
